FROM python:3.10

RUN apt-get update && apt-get install -y git
RUN pip install flask

RUN git clone https://github.com/luisRubiera/epf-ptp-docker-chatgpt-lab.git

WORKDIR /epf-ptp-docker-chatgpt-lab

RUN pip install -r requirements.txt

EXPOSE 5000

ENV  OPENAI_KEY=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 


CMD ["flask","--app","hello","run","--host=0.0.0.0"]
