FROM python:3.10

RUN apt-get update && apt-get install -y git
RUN pip install flask

RUN git clone https://github.com/suying-epf/epf-ptp-docker-chatgpt-lab.git

WORKDIR /epf-ptp-docker-chatgpt-lab

RUN pip install -r requirements.txt

EXPOSE 5000

ENV  OPENAI_KEY=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
 


CMD ["flask","--app","hello","run","--host=0.0.0.0"]
